create table REDACTII(RedId int, Nume varchar2(35) NOT NULL, Adresa varchar2(50) NOT NULL, RedactorSef varchar2(50));

ALTER TABLE REDACTII ADD PRIMARY KEY(REDID);

create table PUBLICATII(PubId int, Nume varchar2(50) NOT NULL, Categorie varchar2(20), Pret Number(8,2) NOT NULL, NrRed int NOT NULL);

ALTER TABLE PUBLICATII ADD PRIMARY KEY(PubId);

ALTER TABLE PUBLICATII ADD FOREIGN KEY(NrRed) REFERENCES REDACTII(RedId) ON DELETE SET NULL;

create table ABONATI(AbnId int, Email varchar2(50), Adresa varchar2(50),  CodPers varchar2(5) NOT NULL);

ALTER TABLE ABONATI ADD PRIMARY KEY(AbnId);

create table PERSFIZ(AbnId int, Nume varchar2(25) NOT NULL, Prenume varchar2(25));
create table PERSJUR(AbnId int, Nume varchar2(25) NOT NULL, tipjur varchar2(10) NOT NULL, Director varchar2(20) NOT NULL);

ALTER TABLE PERSFIZ ADD PRIMARY KEY(AbnId);
ALTER TABLE PERSJUR ADD PRIMARY KEY(AbnId);
ALTER TABLE PERSFIZ ADD FOREIGN KEY(AbnId) REFERENCES ABONATI(AbnId) ON DELETE SET NULL;
ALTER TABLE PERSJUR ADD FOREIGN KEY(AbnId) REFERENCES ABONATI(AbnId) ON DELETE SET NULL;

create table ABONATILA(AbnId int, PubId int, StartDate date, EndDate date, NrPub int NOT NULL);

ALTER TABLE ABONATILA ADD PRIMARY KEY(AbnId, PubId);
ALTER TABLE ABONATILA ADD FOREIGN KEY(AbnId) REFERENCES ABONATI(AbnId) ON DELETE SET NULL;
ALTER TABLE ABONATILA ADD FOREIGN KEY(PubId) REFERENCES PUBLICATII(PubId) ON DELETE SET NULL;
ALTER TABLE ABONATILA ADD CONSTRAINT Abdate CHECK(EndDate>StartDate);


create table EDITIE(PubId int, Aparitie date NOT NULL, NrEditie int);

ALTER TABLE EDITIE ADD PRIMARY KEY(PubId,Aparitie);
ALTER TABLE EDITIE ADD FOREIGN KEY(PubId) REFERENCES PUBLICATII(PubId) ON DELETE SET NULL;


create table TELABN(AbnId int, NrTelAbn varchar2(15));

ALTER TABLE TELABN ADD PRIMARY KEY(AbnId,NrTelAbn);
ALTER TABLE TELABN ADD FOREIGN KEY(AbnId) REFERENCES ABONATI(AbnId) ON DELETE SET NULL;

create table ADRESE(Adresa varchar(50), JudId int NOT NULL, Judet varchar2(25));

ALTER TABLE ADRESE ADD PRIMARY KEY(Adresa);

create table JUDETE(JudId int, Judet varchar2(25), Localitate varchar2(25) NOT NULL);

ALTER TABLE JUDETE ADD PRIMARY KEY(JudId,Judet);
ALTER TABLE ADRESE ADD FOREIGN KEY(JudId,Judet) REFERENCES JUDETE(JudId,Judet) ON DELETE SET NULL;

create table TELRED(RedId int, NrTelRed varchar2(15));


ALTER TABLE TELRED ADD PRIMARY KEY(RedId, NrTelRed);
ALTER TABLE TELRED ADD FOREIGN KEY(RedId) REFERENCES REDACTII(RedId) ON DELETE SET NULL;

create table ANGAJATI(AngId int, Nume varchar2(25) NOT NULL, Prenume varchar2(25), JudId int, Judet varchar2(25));

ALTER TABLE ANGAJATI ADD PRIMARY KEY(AngId); 
ALTER TABLE ANGAJATI ADD FOREIGN KEY(JudId,Judet) REFERENCES JUDETE(JudId,Judet) ON DELETE SET NULL;
ALTER TABLE REDACTII ADD FOREIGN KEY(Adresa) REFERENCES ADRESE (Adresa) ON DELETE SET NULL;
ALTER TABLE ABONATI ADD FOREIGN KEY(Adresa) REFERENCES ADRESE(Adresa) ON DELETE SET NULL;
ALTER TABLE ABONATI ADD CONSTRAINT UniqueEmail Unique(Email);
