-- constrangere de unicitate
-- cu index unic

ALTER TABLE ABONATI ADD CONSTRAINT UniqueEmail UNIQUE(EMAIL) DISABLE VALIDATE;

ALTER TABLE ABONATI MODIFY ADRESA NOT NULL DISABLE VALIDATE;

select constraint_name, constraint_type, status, validated, index_name, rely
from   user_constraints
where  table_name = upper('PUBLICATII');

-- SYS_C007464 = cheie primara
ALTER TABLE PUBLICATII MODIFY CONSTRAINT SYS_C007464 RELY;

select constraint_name, constraint_type, status, validated, index_name, rely
from   user_constraints
where  table_name = upper('LIVRARI');

-- SYS_C007483 = cheie primara
ALTER TABLE LIVRARI MODIFY CONSTRAINT SYS_C007483 RELY;

-- constrangere de cheie
-- primara
ALTER TABLE VANZARI ADD CONSTRAINT PKVANZ PRIMARY KEY(LIVID, PUBID) 
RELY ENABLE NOVALIDATE;

-- cheie externa
ALTER TABLE VANZARI ADD CONSTRAINT FKVANZ FOREIGN KEY(PUBID)
REFERENCES PUBLICATII(PUBID) ENABLE NOVALIDATE;
ALTER TABLE VANZARI ADD CONSTRAINT FKVANZ2 FOREIGN KEY(LIVID)
REFERENCES LIVRARI(LIVID) ENABLE NOVALIDATE;

ALTER TABLE LIVRARI ADD CONSTRAINT FKLIV FOREIGN KEY(NRPUB) REFERENCES
PUBLICATII(PUBID) RELY ENABLE NOVALIDATE;

-- SYS_C007471 = CHEIE PRIMARA
select constraint_name, constraint_type, status, validated, index_name, rely
from   user_constraints
where  table_name = upper('ABONATI');
ALTER TABLE ABONATI MODIFY CONSTRAINT SYS_C007471 RELY;

ALTER TABLE PERSFIZ ADD CONSTRAINT PFFK FOREIGN KEY(ABNID) REFERENCES
ABONATI(ABNID) RELY ENABLE NOVALIDATE;
ALTER TABLE PERSJUR ADD CONSTRAINT PJFK FOREIGN KEY(ABNID) REFERENCES
ABONATI(ABNID) RELY ENABLE NOVALIDATE;

ALTER TABLE ABONATILA ADD CONSTRAINT ABFK FOREIGN KEY(ABNID) REFERENCES
ABONATI(ABNID) ENABLE NOVALIDATE;
ALTER TABLE ABONATILA ADD CONSTRAINT ABFK2 FOREIGN KEY(PUBID) REFERENCES
PUBLICATII(PUBID) ENABLE NOVALIDATE;

ALTER TABLE ABONATILA ADD CONSTRAINT Abdate CHECK(EndDate>StartDate) NOVALIDATE;

select constraint_name, constraint_type, status, validated, index_name, rely
from   user_constraints
where  table_name = upper('ABONATILA');

COMMIT;