DROP TABLE PERSJUR;
DROP TABLE PERSFIZ;
DROP TABLE ABONATILA;
DROP TABLE ABONATI;
DROP TABLE ANGAJATI;
DROP TABLE EDITIE;
DROP TABLE VANZARI;
DROP TABLE LIVRARI;
DROP TABLE PUBLICATII;
DROP TABLE REDACTII;

